language: php
php:
    - '7.3'
before_script:
    - composer self-update
    - composer update --no-interaction --prefer-lowest
    - composer dumpautoload -o
    - composer info | sort
script:
    - composer validate --strict
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpunit